### PR TITLE
Add gthub actions

### PR DESCRIPTION
**Pull request by negiDharmendra**

### CODE REVIEW

**Comment by negiDharmendra** [comment]
@gaugebot recheck the pull request.

**Comment by Apoorva-GA** [comment]
@negiDharmendra It is still running on travis. Can you check?

**Comment by negiDharmendra** [comment]
@Apoorva-GA I have already removed the webhook for travis ci.

**Comment by Apoorva-GA** [comment]
@negiDharmendra Please check the builds. It is still picking up travis check.

**Pull request merged**
